name: Cache Node and npm dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
    required: true
    description: "Node version to use"
    default: "20.x"
  working-dir:
    required: false
    description: The working directory of the application
    default: .
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - id: cache
      uses: actions/cache@v3
      with:
        key: nd-${{ hashFiles(inputs.working-dir) }}/package-lock.json
        path: ${{ inputs.working-dir }}/node_modules
    - name: Install dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        npm ci
        
