name: Cache Node and npm dependencies
description: This action allows to cache both Node and NPM dependencies based on the package-lock.json file.
inputs:
  node-version:
    required: true
    description: "Node version to use"
    default: "20.x"
  working-dir:
    required: false
    description: The working directory of the application
    default: .
  target-env:
    required: false
    description: "dev or prod. Controls whether dev dependencies are installed"
    default: dev
runs:
  using: composite
  steps:
    - name: Setup NodeJS version ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - id: cache
      uses: actions/cache@v3
      with:
        key: nd-${{ inputs.target-env }}-${{ hashFiles(format('{0}/{1}', inputs.working-dir, 'package-lock.json')) }}
        path: ${{ inputs.working-dir }}/node_modules
    - name: Install dependencies
      if: ${{ steps.cache.outputs.cache-hit != 'true' }}
      shell: bash
      working-directory: ${{ inputs.working-dir }}
      run: |
        npm ci ${{ inputs.target-env != 'dev' && '--omit=dev' || '' }}
        
