name: 07 - Expressions
run-name: "07 - Using Expressions - DEBUG: ${{ inputs.debug && 'ON' || 'OFF' }}"
on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: true
        default: false
        description: Run in debug mode?
jobs:
  echo:
    name: Echo some data
    runs-on: ubuntu-latest
    steps:
      - name: "[debug] Print start-up data"
        if: inputs.debug == true
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit SHA: ${{ github.sha }}"
          echo "Runner OS: ${{ runner.os }}"
      - name: "[debug] Print when triggered from main"
        if: inputs.debug == true && github.ref_name == 'main'
        run: |
          echo "I was triggered from main."
      - name: Greeting
        run: |
          echo "Hello World"
