name: 08 - Variables
on:
  workflow_dispatch:
env:
  WORKFLOW_VAR: "I am a workflow env var."
  OVERWRITTEN: "I will be overwritten."
jobs:
  echo:
    name: Echo values
    env:
      JOB_VAR: "I am a job env var."
      OVERWRITTEN: "I have been overwritten on the job level."
    runs-on: ubuntu-latest
    steps:
      - name: Print env variables
        env:
          STEP_VAR: "I am a step env var."
          step_var_2: "I am another step env var."
        run: |
          echo "Step env var: ${STEP_VAR}"
          echo "Another step env var: ${ste_var_2}"
          echo "Job env var: ${{ env.JOB_VAR }}"
          echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
          echo "Overwritten: ${{ env.OVERWRITTEN }}"
      - name: Overwrite job variable
        env:
          OVERWRITTEN: "I have been overwritten at the step level"
        run: |
          echo "Overwritten: $OVERWRITTEN"
