name: 12 - Working with Outputs
on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        required: true
        default: success
        options:
          - failure
          - success
        description: Build status
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }}
      output1: ${{ steps.build.outputs.output1 }}
    steps:
      - name: Output GITHUB_OUTPUT
        id: build
        run: |
          echo "Output path: $GITHUB_OUTPUT"
          echo "status=${{ inputs.build-status }}" >> $GITHUB_OUTPUT
          echo "output1=value1" >> $GITHUB_OUTPUT
          echo "output2=value2" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
          echo "mistake=true" > $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Print Output
        run: |
          echo "${{  needs.build.outputs.output1 }}
      - name: Deploy
        run: |
          echo "Debugging..."
          cat << EOF
            ${{ toJSON(needs.build.outputs) }}
          EOF
          echo "Deploying..."
