name: 13 - Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        required: true
        default: true
        description: Use caching
      node-version:
        type: choice
        required: true
        default: 20.x
        options:
          - 18.x
          - 20.x
          - 21.x
        description: Node version
jobs:
  install-deps:
    name: Install dependencies
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.CACHE_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - id: cache-key
        name: Cache
        run: |
          echo "CACHE_KEY=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> "$GITHUB_OUTPUT"
      - id: cache
        name: Download cached dependencies
        uses: actions/cache@v3
        with:
          key: ${{ steps.cache-key.outputs.CACHE_KEY }}
          path: "13-caching/react-app/node_modules"
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        working-directory: 13-caching/react-app
        run: |
          npm ci
  linting:
    name: Linting
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - name: Use cache
        uses: actions/cache@v3
        with:
          key: ${{ needs.install-deps.outputs.cache-key }}
          path: 13-caching/react-app
      - name: Test
        run:
          npm run test
      - name: Lint
        run: |
          echo "Linting..."
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - id: cache
        name: Download cached dependencies
        uses: actions/cache@v3
        with:
          path: "13-caching/react-app/node_modules"
          key: ${{ needs.install-deps.outputs.cache-key }}
      - name: Run tests
        run: |
          npm run test
      - name: Building
        run: |
          npm run build
      - name: Deploying to nonprod
        run: |
          echo "Deploying to nonprod..."

      
