name: 13 - Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        required: true
        default: true
        description: Use caching
      node-version:
        type: choice
        required: true
        default: 20.x
        options:
          - 18.x
          - 20.x
          - 21.x
        description: Node version
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
      - id: cache
        name: Download cached dependencies
        if: ${{ inputs.use-cache }}
        uses: actions/cache@v3
        with:
          path: "13-caching/react-app/node_modules"
          key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          npm ci
      - name: Run tests
        run: |
          npm run test
      - name: Building
        run: |
          npm run build
      - name: Deploying to nonprod
        run: |
          echo "Deploying to nonprod..."

      
