name: 14 - Artifacts
on:
  workflow_dispatch:
env:
  WORKING_DIRECTORY: 14-artifacts/react-app
jobs:
  test-build:
    name: Test and Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: deps-node-modules-${{ hashFiles('14-artifacts/react-app/package-lock.json') }}
          path: ${{ env.WORKING_DIRECTORY }}/node_modules
      - name: Install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          npm ci
      - name: Unit tests
        run: |
          npm run test
      - name: Build code
        run: |
          npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ env.WORKING_DIRECTORY }}/build
  deploy:
    name: Deploy
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: ${{ env.WORKING_DIRECTORY }}/build
      - name: Show folder structure
        run:
          ls -R
