name: 15 - Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: Check compatibility with ${{ matrix.os }} and Node version ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 21.x]
        include:
          - os: ubuntu-latest
            node-version: 16.x
          - os: ubuntu-latest
            node-version: 21.x
            tag: experimental
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Fail if experimental
        if: ${{ matrix.tag == 'experimental' }}
        run: |
          exit 1
      - name: Perform some tests
        run: |
          echo "Running tests on ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}..."
          sleep 10
      - name: Upload test results
        run: |
          echo "Uploading test results..."
  include-example:
    name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: [red, green, blue]
        shape: [circle, square]
        size: [small, large]
        include:
          - opacity: 50
          - color: red
            opacity: 75
          - shape: circle
            opacity: 100
          - color: red
            shape: triangle
        exclude:
          - color: green
            shape: circle
    steps:
      - name: Dummy step
        run: |
          echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"
          
