name: 15 - Matrices
on:
  workflow_dispatch:
jobs:
  backwards-compatibility:
    name: Check compatibility with ${{ matrix.os }} and Node version ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18.x, 20.x, 21.x]
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Perform some tests
        run: |
          echo "Running tests on ${{ matrix.os }} and NodeJS ${{ matrix.node-version }}..."
