name: 16 - Environments
on:
  workflow_dispatch:
jobs:
  deploy-staging:
    name: Deploy to staging
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Deploying to staging..."
  e2e-tests:
    name: E2E testing
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - name: E2E tests
        run: |
          echo "Running E2E tests..."
  deploy-prod:
    name: Deploy to prod
    environment: prod
    env:
      my-env-value: ${{ vars.MY_ENV_VALUE || 'default value' }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to prod
        run: |
          echo "Deploying to prod with ${{ env.my-env-value }}..."
