name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS
on:
  workflow_dispatch:
jobs:
  dependency-update:
    name: Dependency update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update dependencies
        uses: ./.github/actions/js-dependency-update
